apiVersion: v1
kind: ConfigMap
metadata:

  annotations:

    argocd.argoproj.io/sync-wave: "0"
  name: gamems-config
data:
  # ==========================================
  # SICUREZZA E CORS
  # ==========================================
  HEALTH_SHOW_DETAILS: "never"
  ALLOWED_ORIGINS: "http://gamems.local,https://gamems.local"
  
  # ==========================================
  # RISOLUZIONE DNS KUBERNETES INFRASTRUTTURA
  # ==========================================
  # Definiamo i nomi dei Service K8s a cui i pod dovranno connettersi.
  DB_HOST: "postgres-service.gamems.svc.cluster.local"
  RABBIT_HOST: "rabbitmq-service.gamems.svc.cluster.local"
  REDIS_HOST: "redis-service.gamems.svc.cluster.local"

  # ==========================================
  # UTENTI
  # ==========================================
  PG_ROOT_USER: "root_admin"
  USER_DB_USER: "user_user"
  GAME_DB_USER: "game_user"
  WALLET_DB_USER: "wallet_user"
  RABBIT_USER: "guest"

  # ==========================================
  # RISOLUZIONE DNS KUBERNETES MICROSERVIZI
  # ==========================================
  # Questi nomi verranno letti dal Gateway e dal Game Service per farsi le chiamate interne
  USER_HOST: "user-service.gamems.svc.cluster.local"
  WALLET_HOST: "wallet-service.gamems.svc.cluster.local"
  GAME_HOST: "game-service.gamems.svc.cluster.local"
  MAIL_HOST: "mailpit-service.gamems.svc.cluster.local"