# ==========================================
# GAME SERVICE (Porta 8083)
# ==========================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
  namespace: gamems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
      - name: game-service
        image: game-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms128m -Xmx256m"
        - name: HEALTH_SHOW_DETAILS
          valueFrom: { configMapKeyRef: { name: gamems-config, key: HEALTH_SHOW_DETAILS } }
        - name: WALLET_HOST
          valueFrom: { configMapKeyRef: { name: gamems-config, key: WALLET_HOST } }
        - name: DB_HOST
          valueFrom: { configMapKeyRef: { name: gamems-config, key: DB_HOST } }
        - name: DB_USER
          valueFrom: { configMapKeyRef: { name: gamems-config, key: GAME_DB_USER } }
        - name: DB_PASS
          valueFrom: { secretKeyRef: { name: gamems-secrets, key: GAME_DB_PASS } }
        - name: RABBIT_HOST
          valueFrom: { configMapKeyRef: { name: gamems-config, key: RABBIT_HOST } }
        - name: RABBIT_USER
          valueFrom: { configMapKeyRef: { name: gamems-config, key: RABBIT_USER } }
        - name: RABBIT_PASS
          valueFrom: { secretKeyRef: { name: gamems-secrets, key: RABBIT_PASS } }
        - name: APP_JWT_SECRET
          valueFrom: { secretKeyRef: { name: gamems-secrets, key: APP_JWT_SECRET } }
        - name: APP_INTERNAL_SECRET
          valueFrom: { secretKeyRef: { name: gamems-secrets, key: APP_INTERNAL_SECRET } }
        resources:
          requests: { memory: "256Mi", cpu: "100m" }
          limits: { memory: "512Mi", cpu: "500m" }
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: gamems
spec:
  selector:
    app: game-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083