apiVersion: v1
kind: ConfigMap
metadata:
  name: gamems-config
data:
  # ==========================================
  # SICUREZZA E CORS
  # ==========================================
  HEALTH_SHOW_DETAILS: "never"
  ALLOWED_ORIGINS: "http://localhost:8080,http://localhost,http://localhost:30000"
  
  # ==========================================
  # RISOLUZIONE DNS KUBERNETES INFRASTRUTTURA
  # ==========================================
  # Definiamo i nomi dei Service K8s a cui i pod dovranno connettersi.
  DB_HOST: "postgres-service"
  RABBIT_HOST: "rabbitmq-service"
  REDIS_HOST: "redis-service"

  # ==========================================
  # UTENTI
  # ==========================================
  PG_ROOT_USER: "root_admin"
  USER_DB_USER: "user_user"
  GAME_DB_USER: "game_user"
  WALLET_DB_USER: "wallet_user"
  RABBIT_USER: "guest"

  # ==========================================
  # RISOLUZIONE DNS KUBERNETES MICROSERVIZI
  # ==========================================
  # Questi nomi verranno letti dal Gateway e dal Game Service per farsi le chiamate interne
  USER_HOST: "user-service"
  WALLET_HOST: "wallet-service"